// Object {
//   "actions": Object {
//     "dismiss": [Function dismiss],
//     "goBack": [Function goBack],
//     "navigate": [Function navigate],
//     "pop": [Function pop],
//     "popToTop": [Function popToTop],
//     "push": [Function push],
//     "replace": [Function replace],
//     "reset": [Function reset],
//     "setParams": [Function setParams],
//   },
//   "addListener": [Function addListener],
//   "dangerouslyGetParent": [Function anonymous],
//   "dismiss": [Function anonymous],
//   "dispatch": [Function anonymous],
//   "emit": [Function emit],
//   "getChildNavigation": [Function getChildNavigation],
//   "getParam": [Function anonymous],
//   "getScreenProps": [Function anonymous],
//   "goBack": [Function anonymous],
//   "isFirstRouteInParent": [Function isFirstRouteInParent],
//   "isFocused": [Function isFocused],
//   "navigate": [Function anonymous],
//   "pop": [Function anonymous],
//   "popToTop": [Function anonymous],
//   "push": [Function anonymous],
//   "replace": [Function anonymous],
//   "reset": [Function anonymous],
//   "router": undefined,
//   "setParams": [Function anonymous],
//   "state": Object {
//     "key": "id-1567401586347-1",
//     "params": Object {
//       "lists": Array [
//         Object {
//           "id": 1,
//           "name": "Groceries",
//         },
//         Object {
//           "id": 2,
//           "name": "Laundry",
//         },
//       ],
//     },
//     "routeName": "Lists",
//   },
// }
// Object {
//   "actions": Object {
//     "dismiss": [Function dismiss],
//     "goBack": [Function goBack],
//     "navigate": [Function navigate],
//     "pop": [Function pop],
//     "popToTop": [Function popToTop],
//     "push": [Function push],
//     "replace": [Function replace],
//     "reset": [Function reset],
//     "setParams": [Function setParams],
//   },
//   "addListener": [Function addListener],
//   "dangerouslyGetParent": [Function anonymous],
//   "dismiss": [Function anonymous],
//   "dispatch": [Function anonymous],
//   "emit": [Function emit],
//   "getChildNavigation": [Function getChildNavigation],
//   "getParam": [Function anonymous],
//   "getScreenProps": [Function anonymous],
//   "goBack": [Function anonymous],
//   "isFirstRouteInParent": [Function isFirstRouteInParent],
//   "isFocused": [Function isFocused],
//   "navigate": [Function anonymous],
//   "pop": [Function anonymous],
//   "popToTop": [Function anonymous],
//   "push": [Function anonymous],
//   "replace": [Function anonymous],
//   "reset": [Function anonymous],
//   "router": undefined,
//   "setParams": [Function anonymous],
//   "state": Object {
//     "key": "id-1567401586347-1",
//     "params": Object {
//       "lists": Array [
//         Object {
//           "id": 1,
//           "name": "Groceries",
//         },
//         Object {
//           "id": 2,
//           "name": "Laundry",
//         },
//       ],
//     },
//     "routeName": "Lists",
//   },
// }